# -*- mode: ruby -*-
# vi: set ft=ruby :

VERSION = ENV['DOCKER_VERSION']

Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    config.vm.provision "shell", inline: <<-SHELL

        set -x

        setenforce 0
        sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config

        swapoff -a
        sed -i '/swap/s/^/#/g' /etc/fstab

        sysctl --system

        yum install -y yum-utils device-mapper-persistent-data lvm2

        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

        yum install -y docker-ce-#{VERSION}

        systemctl enable docker && systemctl start docker

        rancher_image="rancher/rancher:v2.2.4"
        rancher_agent_image="rancher/rancher-agent:v2.2.4"
        curl_image="appropriate/curl"
        jq_image="stedolan/jq"

        echo ***************************
        echo pulling images

        docker pull ${rancher_image}       &>/dev/null
        docker pull ${rancher_agent_image} &>/dev/null
        docker pull ${curl_image}          &>/dev/null
        docker pull ${jq_image}            &>/dev/null

        docker images

        systemctl stop postfix ; yum remove -y postfix
        systemctl stop chronyd ; yum remove -y chrony

        dd if=/dev/zero of=/EMPTY bs=1M
        rm -f /EMPTY

        sync

    SHELL

end